[versions]
agp = "8.10.1"
dexkit = "2.0.6"
fastjson2 = "2.0.57"
koin = "4.1.0"
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization-json = "1.8.1"
ktor = "3.1.2"
serialize = "3.0.1"

[libraries]
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
fast-json = { module = "com.alibaba.fastjson2:fastjson2-kotlin", version.ref = "fastjson2" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
serialize = { module = "com.github.liangjingkanji:Serialize", version.ref = "serialize" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
lsplugin-jgit = { id = "org.lsposed.lsplugin.jgit", version = "1.1" }
lsplugin-resopt = { id = "org.lsposed.lsplugin.resopt", version = "1.6" }
lsplugin-lsparanoid = { id = "org.lsposed.lsparanoid", version = "0.6.0" }
